name: posit
description: A Dart implementation of posit (unum) numbers.
version: 0.0.0
repository: https://github.com/beninato8/posit-dart

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  coverage: ^1.6.0
